### ISSUE TITLE
mapping.icp doesn't return the minimizing permutation of indices

### ISSUE THREAD

**Issue by bdice** [glotzerlab/rowan#15]
When using `rowan.mapping.icp`, the algorithm returns a matrix `R` and a translation `t` that map the points in set `X` to set `Y`. However, if the points in `X` and `Y` are permuted (re-ordered), then it's not enough to rotate and translate the points - they must also be permuted.

The permutation of indices that minimizes the mapping is used internally in the Iterative Closest Point algorithm, and it would be helpful to return those indices alongside the rotation matrix `R` and translation `t`.

**Comment by vyasr** [comment]
As we discussed offline, the internal indices are just based on the closest points found when comparing the two configurations. The main value in returning the indices is simply to provide a way to more effectively measure how good the match was. I'm open to returning the indices based on an optional argument (i.e. adding `return_indexes=False` to the signature) if there's a desire to have that available.

**Comment by vyasr** [comment]
@bdice what are your thoughts? I'm not really convinced that this is necessary, but since it's essentially free I would be fine with a PR to optionally return the indexes.
