### ISSUE TITLE
Angle computed by geometry inconsistent with documentation

### ISSUE THREAD

**Issue by malramsay64** [glotzerlab/rowan#21]
The [documentation](https://rowan.readthedocs.io/en/latest/package-geometry.html#rowan.geometry.angle) states that the `rowan.geometry.angle` function is identical to `rowan.geometry.intrinsic_distance(p, np.array([1, 0, 0, 0]))`. However this is not the case for a simple example

```python
>>> rowan.geometry.angle([0, 0, 0, 1])
3.141592653589793
>>> rowan.geometry.intrinsic_distance([0, 0, 0, 1], [1, 0, 0, 0])
1.5707963267948966
```

This is probably a result of the changes in c563e825506f524d3f3d1dc4d04175076f536eaa (ref #4) which don't update the documentation for the angle function.

**Comment by vyasr** [comment]
You're right, thanks for the find!
