### ISSUE TITLE
Equivalent quaternions not working correctly

### ISSUE THREAD

**Issue by bdice** [glotzerlab/rowan#5]
**[Original report](https://bitbucket.org/glotzer/rowan/issue/5) by Vyas Ramasubramani (Bitbucket: [vramasub](https://bitbucket.org/vramasub), GitHub: [vyasr](https://github.com/vyasr)).**

----------------------------------------

The equivalent_orientations argument of mapping.procrustes does not work; for any quaternion that is not the identity, it produces incorrect results.

**Comment by vyasr** [comment]
Fixed in #11
