### ISSUE TITLE
to_axis_angle not working for multiple quaternions?

### ISSUE THREAD

**Issue by bdice** [glotzerlab/rowan#9]
I have several quaternions and want to get axes/angles. This is a traceback of what happens. I'm using rowan v1.2.0.
```
>>> rowan.to_axis_angle(rowan.normalize([[0.707, 0, 0, 0.707], [0, 0, 0, 1]]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bdice/anaconda3/envs/dice/lib/python3.6/site-packages/rowan/functions.py", line 1035, in to_axis_angle
    q[..., 1:]/sines,
ValueError: operands could not be broadcast together with shapes (2,3) (2,)
```

**Comment by bdice** [comment]
Resolved by #10 but hasn't been released yet.

**Comment by vyasr** [comment]
@bdice just FYI the way Github works is that issues that are resolved by a PR containing a commit that actually says "Closes issue X" don't actually get closed until that PR is merged onto whatever the main branch is. Next release I'll switch rowan from Git Flow to OneFlow as well, which will make that happen much faster, but for the auto closes will happen when the next release happens.

**Comment by bdice** [comment]
@vyasr Ah, thanks for clarifying. Sorry about that, I should have left it alone.

**Comment by bdice** [comment]
@vyasr Do you have a timeline in mind for changing to OneFlow and/or making a release with this fix? Just ran into issues with this again.

**Comment by vyasr** [comment]
Thanks for the push. I'll do that this week, probably Thursday.
